Copy and paste the following code to create a calendar table that will allow you to quickly build measures using your standard YOY logic.


let
    //Type desired start date in formula bar
    StartDate = #date(2023, 1, 1),
    //Type desired end date in formula bar
    EndDate = #date(2023,12,31),
    Duration = Duration.Days(Duration.From(EndDate-StartDate))+1,
    Dates = List.Dates(StartDate,Duration,#duration(1,0,0,0)),
    #"Converted to Table" = Table.FromList(Dates, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Renamed Columns" = Table.RenameColumns(#"Converted to Table",{{"Column1", "Date"}}),
    #"Inserted Year" = Table.AddColumn(#"Renamed Columns", "Year", each Date.Year([Date]), Int64.Type),
    #"Inserted Month" = Table.AddColumn(#"Inserted Year", "Month", each Date.Month([Date]), Int64.Type),
    #"Inserted Week of Year" = Table.AddColumn(#"Inserted Month", "Week of Year", each Date.WeekOfYear([Date]), Int64.Type),
    #"Inserted Quarter" = Table.AddColumn(#"Inserted Week of Year", "Quarter", each Date.QuarterOfYear([Date]), Int64.Type),
    #"Get Date LY" = Table.AddColumn(#"Inserted Quarter", "Date LY", each Date.AddDays([Date],-364)),
    #"Get Date LLY" = Table.AddColumn(#"Get Date LY", "Date LLY", each Date.AddDays([Date],-728)),
    #"Format Date columns" = Table.TransformColumnTypes(#"Get Date LLY",{{"Date", type date}, {"Date LY", type date}, {"Date LLY", type date}})
in
    #"Format Date columns"
